# Generated by Django 3.1.1 on 2020-09-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MaeumCheck.meeting')),
                ('maxPeople', models.IntegerField()),
                ('currentPeople', models.IntegerField()),
                ('congestion', models.IntegerField()),
            ],
            bases=('MaeumCheck.meeting',),
        ),
        migrations.CreateModel(
            name='Meeting_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('visiter', models.CharField(max_length=50)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MaeumCheck.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Place_Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('visiter', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MaeumCheck.place')),
            ],
        ),
    ]
